version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: produtos_postgres
    environment:
      POSTGRES_DB: produtosdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - produtos-net
volumes:
  pgdata:
networks:
  produtos-net: